import React, { useEffect, useMemo, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import { AlertCircle, ArrowLeft, Bell, CalendarDays, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, FileUp, MapPin, X } from "lucide-react";
import DatePicker from "../components/DatePicker";

const key = date => `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
const monday = date => { const d = new Date(date); d.setDate(d.getDate() - ((d.getDay() + 6) % 7)); d.setHours(12,0,0,0); return d; };
const weekday = [[1,"一"],[2,"二"],[3,"三"],[4,"四"],[5,"五"],[6,"六"],[0,"日"]];
function showAcademicToast(notice) { window.dispatchEvent(new CustomEvent("academic:toast",{detail:notice})); }
function AcademicToastHost() { const [notice,setNotice]=useState(null); useEffect(()=>{const show=event=>setNotice(event.detail);window.addEventListener("academic:toast",show);return()=>window.removeEventListener("academic:toast",show)},[]); useEffect(()=>{if(!notice)return undefined;const timer=window.setTimeout(()=>setNotice(null),4200);return()=>window.clearTimeout(timer)},[notice]); if(!notice)return null; const Icon=notice.type==="error"?AlertCircle:CheckCircle2; return <div className={`academic-toast ${notice.type||"success"}`} role={notice.type==="error"?"alert":"status"}><Icon size={19}/><div><strong>{notice.title}</strong><span>{notice.message}</span></div><button onClick={()=>setNotice(null)} aria-label="关闭提示"><X size={16}/></button></div>; }
function Shell({ title, children }) { const nav=useNavigate(); return <main className="academic-page"><header><button className="icon-button" onClick={()=>nav("/")} aria-label="返回主页"><ArrowLeft size={20}/></button><div><p>本地校园助手</p><h1>{title}</h1></div></header><AcademicToastHost/>{children}</main>; }
function Reminder({ settings, onSave }) { return <label className="academic-reminder"><Bell size={17}/><input type="checkbox" checked={settings.enabled} onChange={e=>onSave({...settings,enabled:e.target.checked})}/><span>开启提醒</span><input type="number" min="0" value={settings.reminderMinutes} disabled={!settings.enabled} onChange={e=>onSave({...settings,reminderMinutes:e.target.value})}/><span>分钟前</span></label>; }
function WeekPicker({ open, selectedWeek, maxWeek, onClose, onConfirm }) { const [draft,setDraft]=useState(selectedWeek); const activeRef=useRef(null); useEffect(()=>{setDraft(selectedWeek); if(open) requestAnimationFrame(()=>activeRef.current?.scrollIntoView({ block:"center" }));},[selectedWeek,open]); if(!open)return null; return <section className="week-picker"><header><button onClick={onClose}>取消</button><strong>选择周次</strong><button onClick={()=>onConfirm(draft)}>确定</button></header><div className="week-picker-list">{Array.from({length:maxWeek},(_,index)=>index+1).map(item=><button ref={item===draft?activeRef:null} key={item} className={item===draft?"active":""} onClick={()=>setDraft(item)}>第{item}周</button>)}</div></section>; }
export function ScheduleApp() {
  const [data,setData]=useState(null); const [day,setDay]=useState(new Date().getDay()); const [start,setStart]=useState(""); const [viewWeek,setViewWeek]=useState(null); const [pickerOpen,setPickerOpen]=useState(false); const [jumpDate,setJumpDate]=useState(key(new Date()));
  useEffect(()=>{window.academicApi.getSchedule().then(d=>{setData(d);setStart(d.startDate||"")});return window.academicApi.onScheduleChanged(setData)},[]);
  const today=new Date(); const currentWeek=useMemo(()=>data?.startDate?Math.floor((monday(today)-monday(new Date(`${data.startDate}T12:00:00`)))/604800000)+1:null,[data?.startDate]); const maxWeek=useMemo(()=>Math.max(1,...(data?.courses||[]).map(c=>c.endWeek)),[data?.courses]); const week=Math.max(1,Math.min(maxWeek,viewWeek??currentWeek??1)); const weekStart=useMemo(()=>{if(!data?.startDate)return null;const d=monday(new Date(`${data.startDate}T12:00:00`));d.setDate(d.getDate()+(week-1)*7);return d},[data?.startDate,week]);
  const courses=useMemo(()=>!data||!week?[]:data.courses.filter(c=>c.weekday===day&&week>=c.startWeek&&week<=c.endWeek&&(c.pattern==="每周"||(c.pattern==="单周"?week%2:week%2===0))).sort((a,b)=>a.period-b.period),[data,day,week]);
  async function importFile(){try{const r=await window.academicApi.importSchedule(start);if(r.status==="imported")showAcademicToast({title:"课表导入完成",message:`已识别并保存${r.count}节课程。`})}catch(e){showAcademicToast({type:"error",title:"课表导入失败",message:e.message||"请检查文件格式后重试。"})}}
  function jumpToDate(value){setJumpDate(value);if(!data?.startDate||!value)return;const target=new Date(`${value}T12:00:00`);const first=monday(new Date(`${data.startDate}T12:00:00`));const targetWeek=Math.floor((monday(target)-first)/604800000)+1;setViewWeek(Math.max(1,Math.min(maxWeek,targetWeek)));setDay(target.getDay());}
  if(!data)return null; return <Shell title="日常课表"><section className="academic-toolbar"><div><label>开学日期 <DatePicker value={start} onChange={setStart} ariaLabel="开学日期"/></label><button className="primary-button" disabled={!start} onClick={importFile}><FileUp size={17}/>导入课表</button><label className="jump-date"><CalendarDays size={16}/>查看日期 <DatePicker value={jumpDate} onChange={jumpToDate} ariaLabel="查看日期"/></label></div><Reminder settings={data.settings} onSave={s=>window.academicApi.saveScheduleSettings(s)}/></section><div className="week-title"><div className="week-switch"><button className="week-prev" onClick={()=>setViewWeek(week-1)} disabled={week<=1} aria-label="上一教学周"><ChevronLeft size={19}/></button><button className="week-select" onClick={()=>setPickerOpen(value=>!value)}>第 {week} 教学周 <ChevronDown size={18}/></button><button className="week-next" onClick={()=>setViewWeek(week+1)} disabled={week>=maxWeek} aria-label="下一教学周"><ChevronRight size={19}/></button>{viewWeek!==null&&<button className="week-today" onClick={()=>setViewWeek(null)}>回到当前周</button>}<WeekPicker open={pickerOpen} selectedWeek={week} maxWeek={maxWeek} onClose={()=>setPickerOpen(false)} onConfirm={next=>{setViewWeek(next);setPickerOpen(false)}}/></div></div><nav className="weekday-tabs">{weekday.map(([value,name])=>{const date=weekStart?new Date(weekStart.getFullYear(),weekStart.getMonth(),weekStart.getDate()+((value+6)%7)):null;return <button key={name} className={day===value?"active":""} onClick={()=>setDay(value)}><span>周{name}</span>{date&&<small>{date.getMonth()+1}.{date.getDate()}</small>}</button>})}</nav><section className="course-list">{courses.length?courses.map(c=><article className="course-card" key={c.id}><time><b>{c.startTime}</b><span>至 {c.endTime}</span></time><div><strong>{c.name}</strong>{c.location&&<em><MapPin size={17}/>{c.location}</em>}</div></article>):<div className="academic-empty">当天没有课程</div>}</section></Shell>;
}
export function ExamsApp() {
  const [data,setData]=useState(null); const [month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1)); const [selected,setSelected]=useState(key(new Date()));
  useEffect(()=>{window.academicApi.getExams().then(setData);return window.academicApi.onExamsChanged(setData)},[]); const exams=data?.exams||[]; const selectedExams=exams.filter(e=>e.date===selected);
  const cells=useMemo(()=>{const first=monday(month);const start=new Date(first);start.setDate(start.getDate()-((first.getDay()+6)%7));return Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return d})},[month]);
  async function importFile(){try{const r=await window.academicApi.importExams();if(r.status==="imported"){showAcademicToast({title:"考试信息导入完成",message:`已识别${r.count}场考试，新增${r.todoAdded||0}项P0考试待办。`});setMonth(new Date(`${data?.exams?.[0]?.date||key(new Date())}T12:00:00`))}}catch(e){showAcademicToast({type:"error",title:"考试信息导入失败",message:e.message||"请检查文件格式后重试。"})}}
  if(!data)return null; return <Shell title="考试信息"><section className="academic-toolbar"><button className="primary-button" onClick={importFile}><FileUp size={17}/>导入考试表</button><Reminder settings={data.settings} onSave={s=>window.academicApi.saveExamSettings(s)}/></section><section className="exam-layout"><div className="exam-calendar"><div className="calendar-head"><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}><ChevronLeft/></button><strong>{month.toLocaleDateString("zh-CN",{year:"numeric",month:"long"})}</strong><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}><ChevronRight/></button></div><div className="calendar-grid">{["一","二","三","四","五","六","日"].map(d=><b key={d}>{d}</b>)}{cells.map(d=>{const k=key(d),count=exams.filter(e=>e.date===k).length;return <button key={k} onClick={()=>setSelected(k)} className={`${d.getMonth()===month.getMonth()?"":"muted"} ${selected===k?"selected":""} ${count?"has-exam":""}`}>{d.getDate()}{count>0&&<i>{count}</i>}</button>})}</div></div><aside className="exam-detail"><p>{new Date(`${selected}T12:00:00`).toLocaleDateString("zh-CN",{month:"long",day:"numeric",weekday:"long"})}</p>{selectedExams.slice(0,3).length?selectedExams.slice(0,3).map(e=><article key={e.id}><strong>{e.name}</strong><span className="exam-time">{e.time||"时间待定"}</span><em><MapPin size={18}/>{e.location||"地点待定"}</em><small>{e.duration}{e.stage&&` · ${e.stage}`}</small></article>):<div className="academic-empty">当天没有考试</div>}</aside></section></Shell>;
}
