// 模型只负责选择工具和参数；所有用户可见的数据回复都由本地固定格式器生成。
const ASSISTANT_TOOLS = [
  { name: "math.calculate", description: "计算纯数值算式，供后续工具引用。", required: ["expression"], properties: { expression: "数字与加减乘除括号", resultKey: "结果引用名，可选" } },
  { name: "app.settings.get", description: "查询工具箱通用设置。", required: [], properties: {} },
  { name: "app.settings.update", description: "修改关闭行为、开机启动或主窗口快捷键。", required: ["patch"], properties: { patch: "showClosePrompt/closeAction(hide|quit)/mainWindowShortcut/launchAtLogin" } },
  { name: "app.open_module", description: "在电脑上打开工具箱指定模块。", required: ["module"], properties: { module: "home/settings/water/todo/pomodoro/finance/schedule/exams" } },
  { name: "app.update.status", description: "查询电脑端版本和更新状态。", required: [], properties: {} },
  { name: "app.update.check", description: "让电脑端检查更新。", required: [], properties: {} },
  { name: "app.update.download", description: "让电脑端下载已发现的更新。", required: [], properties: {} },
  { name: "app.update.install", description: "退出电脑端并安装已下载更新，必须明确确认。", required: ["confirmed"], properties: { confirmed: "必须为true" } },
  { name: "water.add", description: "记录饮水，可补记日期和时间。", required: [], properties: { ml: "number，可选", date: "YYYY-MM-DD，可选", time: "HH:mm，可选" } },
  { name: "water.status", description: "查询今日饮水进度。", required: [], properties: {} },
  { name: "water.history", description: "查询饮水历史与统计。用户问近N天、本周、本月或某日期时必须使用。", required: [], properties: { date: "YYYY-MM-DD", month: "YYYY-MM", startDate: "YYYY-MM-DD", endDate: "YYYY-MM-DD", days: "最近N天，含今天", scope: "selected或all，默认selected", details: "是否列出每日明细，默认true" } },
  { name: "water.undo_last", description: "撤回今天最近一杯水。", required: [], properties: {} },
  { name: "water.settings.get", description: "查询饮水杯型、目标与提醒设置。", required: [], properties: {} },
  { name: "water.settings.update", description: "修改饮水设置，与电脑端设置页能力一致。", required: ["patch"], properties: { patch: "targetCups/selectedCupId/cupProfiles/workStart/workEnd/staleMinutes/repeatUntilLogged/snoozeMinutes/progressMode" } },
  { name: "todo.create", description: "创建待办，可同时创建子任务。", required: ["title"], properties: { title: "string", priority: "P0-P3", description: "string", dueDate: "ISO日期时间", reminderMinutes: "number", tags: "string[]", subtasks: "{title,completed?}[]" } },
  { name: "todo.list", description: "查询待办详情。", required: [], properties: { text: "关键词", completed: "boolean", dueDate: "YYYY-MM-DD", tag: "标签", priority: "P0-P3" } },
  { name: "todo.update", description: "修改待办。", required: ["taskId", "patch"], properties: { taskId: "真实ID或$last_todo", patch: "title/priority/description/dueDate/reminderMinutes/tags" } },
  { name: "todo.complete", description: "完成或恢复待办。", required: ["taskId"], properties: { taskId: "真实ID或$last_todo", completed: "boolean，默认true" } },
  { name: "todo.delete", description: "删除待办。", required: ["taskId"], properties: { taskId: "真实ID或$last_todo" } },
  { name: "todo.subtask.add", description: "给待办新增子任务。", required: ["taskId", "title"], properties: { taskId: "真实ID或$last_todo", title: "string" } },
  { name: "todo.subtask.update", description: "修改或完成子任务。", required: ["taskId", "subtaskId", "patch"], properties: { taskId: "真实ID或$last_todo", subtaskId: "真实ID", patch: "title/completed" } },
  { name: "todo.subtask.delete", description: "删除子任务。", required: ["taskId", "subtaskId"], properties: { taskId: "真实ID或$last_todo", subtaskId: "真实ID" } },
  { name: "todo.reorder", description: "按真实ID调整待办顺序。", required: ["orderedIds"], properties: { orderedIds: "待办ID数组" } },
  { name: "todo.subtask.reorder", description: "按真实ID调整某待办的子任务顺序。", required: ["taskId", "orderedIds"], properties: { taskId: "真实ID或$last_todo", orderedIds: "子任务ID数组" } },
  { name: "todo.tag.add", description: "新增待办标签。", required: ["name"], properties: { name: "string" } },
  { name: "todo.tag.delete", description: "删除待办标签并从待办中移除。", required: ["name"], properties: { name: "string" } },
  { name: "pomodoro.status", description: "查询当前专注、专注任务和今日概况。", required: [], properties: {} },
  { name: "pomodoro.start", description: "开始专注计时。", required: ["title"], properties: { title: "string", minutes: "倒计时分钟；省略为正计时", tags: "string[]" } },
  { name: "pomodoro.finish", description: "结束当前专注。", required: [], properties: { status: "completed或abandoned" } },
  { name: "pomodoro.create_task", description: "创建专注任务。", required: ["title"], properties: { title: "string", minutes: "number", mode: "countdown或countup", tags: "string[]" } },
  { name: "pomodoro.task.list", description: "查询专注任务。", required: [], properties: { text: "关键词", tag: "标签" } },
  { name: "pomodoro.task.update", description: "修改专注任务。", required: ["taskId", "patch"], properties: { taskId: "真实ID或$last_pomodoro_task", patch: "title/minutes/mode/tags" } },
  { name: "pomodoro.task.delete", description: "删除专注任务。", required: ["taskId"], properties: { taskId: "真实ID或$last_pomodoro_task" } },
  { name: "pomodoro.history", description: "查询专注历史和统计。", required: [], properties: { date: "YYYY-MM-DD", month: "YYYY-MM", startDate: "YYYY-MM-DD", endDate: "YYYY-MM-DD", days: "最近N天", tag: "标签", status: "completed或abandoned", details: "boolean", limit: "number" } },
  { name: "pomodoro.history.clear", description: "清空全部专注历史，必须先由用户明确确认。", required: ["confirmed"], properties: { confirmed: "必须为true" } },
  { name: "pomodoro.tag.add", description: "新增专注标签。", required: ["name"], properties: { name: "string" } },
  { name: "pomodoro.tag.delete", description: "删除专注标签。", required: ["name"], properties: { name: "string" } },
  { name: "pomodoro.settings.get", description: "查询番茄钟外观设置。", required: [], properties: {} },
  { name: "pomodoro.settings.update", description: "修改番茄钟表盘或氛围。", required: ["patch"], properties: { patch: "clockStyle/ambience" } },
  { name: "pomodoro.immersive", description: "在电脑上开启或退出沉浸专注界面。", required: ["enabled"], properties: { enabled: "boolean" } },
  { name: "finance.create", description: "新增收入或支出。", required: ["amount"], properties: { type: "expense或income", amount: "数字、算式或$结果", tag: "标签", note: "备注", date: "YYYY-MM-DD" } },
  { name: "finance.batch_create", description: "一次新增多笔账单。", required: ["entries"], properties: { entries: "finance.create参数数组" } },
  { name: "finance.list", description: "查询账单。单日按备注、金额、标签、日期输出；多日先按日期分组。近N天查询传days。", required: [], properties: { text: "关键词", type: "expense或income", amount: "number", tag: "标签", date: "YYYY-MM-DD", month: "YYYY-MM", startDate: "YYYY-MM-DD", endDate: "YYYY-MM-DD", days: "最近N天", includeEmptyDates: "boolean", limit: "number" } },
  { name: "finance.summary", description: "统计任意日期范围的收入、支出、结余和支出分类。", required: [], properties: { date: "YYYY-MM-DD", month: "YYYY-MM", startDate: "YYYY-MM-DD", endDate: "YYYY-MM-DD", days: "最近N天" } },
  { name: "finance.update", description: "修改账单；可用真实ID或match定位。", required: ["patch"], properties: { entryId: "真实ID或$last_finance", match: "text/amount/date/tag", patch: "amount/tag/note/date/type" } },
  { name: "finance.delete", description: "删除账单。", required: ["entryId"], properties: { entryId: "真实ID或$last_finance" } },
  { name: "finance.create_and_link_total", description: "新增账单并关联到总计项目。", required: ["entry", "totalName"], properties: { entry: "finance.create参数", totalName: "string" } },
  { name: "finance.tag.list", description: "查询收入或支出标签。", required: [], properties: { type: "expense或income" } },
  { name: "finance.tag.add", description: "新增自定义账单标签。", required: ["type", "name"], properties: { type: "expense或income", name: "string" } },
  { name: "finance.tag.rename", description: "重命名自定义账单标签并同步历史账单。", required: ["type", "oldName", "newName"], properties: { type: "expense或income", oldName: "string", newName: "string" } },
  { name: "finance.tag.delete", description: "删除或隐藏账单标签。", required: ["type", "name"], properties: { type: "expense或income", name: "string" } },
  { name: "finance.tag.reorder", description: "调整账单标签顺序。", required: ["type", "orderedTags"], properties: { type: "expense或income", orderedTags: "string[]" } },
  { name: "finance.backup.export", description: "把完整记账数据导出到电脑JSON文件。", required: [], properties: { filePath: "可选，电脑上的.json路径；默认文档目录" } },
  { name: "finance.backup.import", description: "从电脑JSON文件覆盖恢复记账数据，必须明确确认。", required: ["filePath", "confirmed"], properties: { filePath: "电脑上的.json路径", confirmed: "必须为true" } },
  { name: "total.create", description: "创建总计项目。", required: ["name"], properties: { name: "string" } },
  { name: "total.list", description: "查询总计项目、累计金额和明细数量。", required: [], properties: { text: "项目名关键词" } },
  { name: "total.update", description: "重命名总计项目。", required: ["totalName", "patch"], properties: { totalName: "当前项目名", patch: "name" } },
  { name: "total.delete", description: "删除总计项目。", required: ["totalName"], properties: { totalName: "string" } },
  { name: "total.record.create", description: "向总计项目添加独立记录。", required: ["totalName", "amount"], properties: { totalName: "string", amount: "number", note: "string", date: "YYYY-MM-DD" } },
  { name: "total.record.list", description: "查询总计项目明细。", required: ["totalName"], properties: { totalName: "string", limit: "number" } },
  { name: "total.record.update", description: "修改总计独立记录。", required: ["totalName", "recordId", "patch"], properties: { totalName: "string", recordId: "真实ID", patch: "amount/note/date" } },
  { name: "total.record.delete", description: "删除总计独立记录。", required: ["totalName", "recordId"], properties: { totalName: "string", recordId: "真实ID" } },
  { name: "total.link_bill", description: "把已有账单关联到总计项目。", required: ["entryId", "totalName"], properties: { entryId: "真实ID或$last_finance", totalName: "string" } },
  { name: "total.unlink_bill", description: "取消账单与总计项目关联，不删除原账单。", required: ["entryId", "totalName"], properties: { entryId: "真实ID", totalName: "string" } },
  { name: "academic.schedule.query", description: "查询已导入课表。查询周一至周日时传 weekday（周日为0、周一为1至周六为6），必须返回该星期全部课程及各自教学周范围；查询具体日期时传 date，必须按日期对应的星期和教学周共同筛选。", required: [], properties: { date: "YYYY-MM-DD", weekday: "0-6，周日为0、周一为1", week: "教学周数字" } },
  { name: "academic.schedule.settings.get", description: "查询课表开学日期和提醒设置。", required: [], properties: {} },
  { name: "academic.schedule.settings.update", description: "修改课表提醒设置或开学日期。", required: ["patch"], properties: { patch: "enabled/reminderMinutes/startDate" } },
  { name: "academic.schedule.import", description: "从电脑本地课表文件导入课程。", required: ["filePath", "startDate"], properties: { filePath: "电脑上的课表文件路径", startDate: "YYYY-MM-DD" } },
  { name: "academic.exams.query", description: "查询实际保存的考试信息，可按单日、月份或日期范围筛选；结果按考试日期分组，每场依次显示科目、考试时间、考试地点。", required: [], properties: { date: "YYYY-MM-DD", month: "YYYY-MM", startDate: "YYYY-MM-DD", endDate: "YYYY-MM-DD", days: "最近N天，含今天" } },
  { name: "academic.exams.settings.get", description: "查询考试提醒设置。", required: [], properties: {} },
  { name: "academic.exams.settings.update", description: "修改考试提醒设置。", required: ["patch"], properties: { patch: "enabled/reminderMinutes" } },
  { name: "academic.exams.import", description: "从电脑本地DOC文件导入考试信息。", required: ["filePath"], properties: { filePath: "电脑上的.doc路径" } }
];

const ASSISTANT_TOOL_NAMES = new Set(ASSISTANT_TOOLS.map(tool => tool.name));
function assistantToolProtocol() { return JSON.stringify(ASSISTANT_TOOLS); }
function normalizeMathExpression(value) { return String(value ?? "").replace(/（/g, "(").replace(/）/g, ")").trim(); }
module.exports = { ASSISTANT_TOOLS, ASSISTANT_TOOL_NAMES, assistantToolProtocol, normalizeMathExpression };
